# Generated by Django 2.2 on 2020-08-19 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='material',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='persona',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Alumno'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Libro'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Profesor'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='revista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Revista'),
        ),
    ]
