# Generated by Django 2.2 on 2020-08-19 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20200819_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='revista',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='Material',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Material'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='persona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Persona'),
        ),
    ]
