# Generated by Django 2.2 on 2020-08-19 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20200819_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Libro')),
                ('revista', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Revista')),
            ],
        ),
    ]
