# Generated by Django 2.2 on 2020-08-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_tipomaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='adeuda',
            field=models.BooleanField(null=True),
        ),
    ]
