# Generated by Django 2.2 on 2020-08-20 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_auto_20200819_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Alumno')),
                ('profesor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Profesor')),
            ],
        ),
        migrations.DeleteModel(
            name='AlumnoAdmin',
        ),
    ]
