# Generated by Django 2.2 on 2020-08-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_auto_20200819_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='Material',
            new_name='material',
        ),
    ]
