# Generated by Django 2.2 on 2020-08-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_auto_20200819_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='foto_portada',
            field=models.ImageField(blank=True, default='fotos_tapa/default.png', upload_to='fotos_tapa/'),
        ),
    ]
