# Generated by Django 2.2 on 2020-08-20 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_auto_20200819_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='foto_portada',
        ),
    ]
