# Generated by Django 2.2 on 2020-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_remove_libro_foto_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='foto_portada',
            field=models.ImageField(blank=True, default='/default.png', upload_to=''),
        ),
    ]
